### ISSUE TITLE
How to load only CLIP from checkpoint

### ISSUE THREAD

**Issue by aikitoria** [comfyanonymous/ComfyUI_TensorRT#15]
Since the TensorRT Loader node only gives us the model, we still need to get CLIP from somewhere else. But the Load Checkpoint node seems to load the entire model into VRAM again even if the Model output is disconnected. How to load only correct CLIP for the checkpoint to use with the TensorRT engine?

Do all SDXL models use the same CLIP model?

**Comment by FoundSol** [comment]
Use Clip Save and VAE Save nodes, then save from another checkpoint. Use Load CLIP and Load VAE nodes to load. ComfyUI usually saves in the output folder.

**Comment by FoundSol** [comment]
Just to add, if yr using a XL model, then use Dual Clip Loader node, because you need to load Clip_G and Clip_L

**Comment by aikitoria** [comment]
I was just typing to ask about those two files as you posted the answer, lol

Can confirm that it works to pass those to TensorRT sampler!
