### ISSUE TITLE
Efficient Loader Node appears to enable the loading of LoRAs.

### ISSUE THREAD

**Issue by JPW0080** [comfyanonymous/ComfyUI_TensorRT#20]
Has anyone else noticed that the Efficient Loader Node appears to enable the loading LoRA's? Currently only tested static batch-1-512x512 on 1.5 realisticVisionV60B1_v51HyperVAE. The speedup is definitely still there on my 3090.

https://github.com/jags111/efficiency-nodes-comfyu

Notice the darkened tone from the nighttime_v1 LoRA:

![Efficient-Loader-0](https://github.com/comfyanonymous/ComfyUI_TensorRT/assets/104588046/ed9328e3-f03e-4a92-a28a-3d1ee874d8d7)

Without LoRA:

![Efficient-Loader-1](https://github.com/comfyanonymous/ComfyUI_TensorRT/assets/104588046/abebe0aa-20bf-4351-98b3-2ab4ddc7701a)

**Comment by mcmonkey4eva** [comment]
Yes, TensorRT model goes straight to the ksampler. If you don't put a lora in between the two, then there's no lora applied.

Loras can also affect the CLIP setup, and that is what you applied the lora to: CLIP. You didn't apply it to the TensorRT'd main model.

**Comment by JPW0080** [comment]
Understood.
