### ISSUE TITLE
With the current security level configuration, only custom nodes from the "default channel" can be installed.

### ISSUE THREAD

**Issue by AlexD81** [comfyanonymous/ComfyUI_TensorRT#6]
Hi, I'm getting error
With the current security level configuration, only custom nodes from the "default channel" can be installed.

how to properly install it? 
thanks

**Comment by WeirdScienceX** [comment]
That sounds like a comfyui manager issue, are you up to date? 

![image](https://github.com/comfyanonymous/ComfyUI_TensorRT/assets/1296569/2c4d8c0e-4972-45dc-a3aa-cd2cac47393b)

**Comment by warudokiruhya** [comment]
Im up to date, and security level says normal too, and I still get that error for basically everything I want to install, like ComfyUI Nodes for Inference.Core and TatToolkit

**Comment by AlexD81** [comment]
my issue was resolved when i tried to update comfy multiple times.  Seems,  there some issue with updates,   so sometimes you should triy to update, don't know, maybe 10 times,  if doesn't help, then try again in half day or so.

**Comment by warudokiruhya** [comment]
It keeps saying up to date
Am 16. Aug. 2024, 15:10 +0900 schrieb AlexD81 ***@***.***>:

**Comment by FruitPigFoot** [comment]
@warudokiruhya you tried updating the manager? Mine worked when i upgraded comfyui manager

**Comment by jayzeng** [comment]
Ran into the same issue, was able to work around it by changing `security_level = weak`

My config below: 

```
(venv) (base) ➜  ComfyUI git:(master) ✗ cat ./custom_nodes/ComfyUI-Manager/config.ini
[default]
preview_method = auto
badge_mode = none
git_exe =
channel_url = https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/node_db/dev
share_option = all
bypass_ssl = False
file_logging = True
default_ui = none
component_policy = workflow
double_click_policy = copy-all
windows_selector_event_loop_policy = False
model_download_by_agent = False
downgrade_blacklist =
security_level = weak
```

**Comment by TheGhostNinja** [comment]
So here are the step : 
![image](https://github.com/user-attachments/assets/d0f9b4ce-3adf-4030-acfd-7d59e0df0835)

1. Change the "channel" in the manager to "channel : dev". Try to install.

2.  "If the error **"With the current security level configuration, only custom nodes from the "default channel" can be installed."** is popping, then go to ...\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager and open the config.ini with the notepad. 

3. Change the value :  security_level = normal to security_level = weak
 
 4. Try to install again the missing node. It should work. 
 
Thanks jayzeng a lot for the solution.

**Comment by WeirdScienceX** [comment]
> So here are the step : ![image](https://private-user-images.githubusercontent.com/130002121/369631612-d0f9b4ce-3adf-4030-acfd-7d59e0df0835.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NDQxOTcsIm5iZiI6MTcyNjk0Mzg5NywicGF0aCI6Ii8xMzAwMDIxMjEvMzY5NjMxNjEyLWQwZjliNGNlLTNhZGYtNDAzMC1hY2ZkLTdkNTllMGRmMDgzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxODM4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZDZiMGY5MmM2Y2U5NjliMmMxMTJlZGI3OWVhODMyYzUzODcwYzIxZTY2Y2NmZjQ2NGM3NmIxOTkzYmQzOTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OLPKXxMhswT9K7jOBEodMCJe57_Sy5dFaazAUWYP_DA)
> 
>     1. Change the "channel" in the manager to "channel : dev". Try to install.
> 
>     2. "If the error **"With the current security level configuration, only custom nodes from the "default channel" can be installed."** is popping, then go to ...\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager and open the config.ini with the notepad.
> 
>     3. Change the value :  security_level = normal to security_level = weak
> 
>     4. Try to install again the missing node. It should work.
> 
> 
> Thanks jayzeng a lot for the solution.

Actually, no need to weaken it that much.  https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#security-policy

`security_level = normal-`  would be better.

**Comment by mdkberry** [comment]
my config.ini was in `ComfyUI_windows_portable\ComfyUI\user\default\ComfyUI-Manager` so might have a new location if you cant find it.

**Comment by R3G4L101** [comment]
"ComfyUI\user\default\ComfyUI-Manager\config.ini"

This should be the new location

**Comment by euss3** [comment]
I did weak and it didnt changes, the error only appears when i try to install nightly version of WanVideoWrapper

**Comment by logan683** [comment]
> So here are the step : ![image](https://github.com/user-attachments/assets/d0f9b4ce-3adf-4030-acfd-7d59e0df0835)
> 
> 1. Change the "channel" in the manager to "channel : dev". Try to install.
> 2. "If the error **"With the current security level configuration, only custom nodes from the "default channel" can be installed."** is popping, then go to ...\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager and open the config.ini with the notepad.
> 3. Change the value :  security_level = normal to security_level = weak
> 4. Try to install again the missing node. It should work.
> 
> Thanks jayzeng a lot for the solution.

Changing channel to channel:dev worked.  Thank you very much.

Edit: I was also trying to install WanVideoWrapper nightly.  Installed fine after changing channels.

**Comment by alessandroperilli** [comment]
The new location for the `config.ini` file is `/comfyui/user/__manager/`, as described [here](https://github.com/Comfy-Org/ComfyUI-Manager/blob/main/docs/en/v3.38-userdata-security-migration.md).
