### ISSUE TITLE
Results in random black image generation.

### ISSUE THREAD

**Issue by WeirdScienceX** [comfyanonymous/ComfyUI_TensorRT#7]
Using 1.5 dynamic workflow, generation will randomly result in a black image.

Tried it with batch sizes 1,2,4,8

I see these warnings in the terminal:

D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py:1408: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))

**Comment by mpiquero1111** [comment]
same error with SD1.5 static tensorRT. First time the images come out ok, the next time black.

**Comment by IdiotSandwichTheThird** [comment]
For me it isn't random, it produces _only_ black images.

**Comment by aikitoria** [comment]
I also seem to get these with low frequency. It doesn't crash the server, so just regenerating fixes it.

**Comment by VGF64** [comment]
I found out that the black images occur consistently when there's a lot of words in the prompt.

**Comment by dicksondickson** [comment]
I'm also getting black images. No errors during the engine creation process and image generation process.

**Comment by sjuxax** [comment]
Seems to happen to me with certain sampler/scheduler combinations. Try changing those up and seeing if it persists.

**Comment by Chalice** [comment]
I noticed an interesting phenomenon here:
I created a static SDXL model with optimal batch size 1, because I generate single images. And I always got black images.

Out of frustration I grabbed one of the provided workflows ( Create_SDXL_Base_TT_Static.json ) and blindly ran it - and I got results!
The reason: Batch size 2. The *first* image in the batch always was black. The second had a good result.
For some reason, the first image in a batch turns black - and if your batch size is only 1, well...

**Comment by aikitoria** [comment]
That doesn't happen for me, batch size does not seem to affect the images being black or not. They're either all black or all good.

**Comment by Chalice** [comment]
Further testing on my side:
the 'optimal batch size' setting of static models essentially specifies the amount of black images I get, heh.
Set optimal batch size to 2, get 2 black images as the first images in a 3 image batch.

**Comment by aikitoria** [comment]
That doesn't even make sense though, a static model with batch size 2 should not be capable of generating a batch of 3 images at all.

**Comment by Chalice** [comment]
Yet here we are. I am now creating a dynamic model with 'static' batch size 1's and fixed 1024 scales for more testing.

**Comment by Chalice** [comment]
Same result. Now creating a dynamic model with a 1-2-3 batch setting.

**Comment by Chalice** [comment]
Result:
A dynamic engine with a 1 2 3 setting (min, opt, max) gives me 3 black images in a batch. It is, for some reason, the max setting.

**Comment by Chalice** [comment]
Note: SD 1.5 works fine for me. Pony does not.

**Comment by aikitoria** [comment]
I've so far tried 1.5, xl and pony and they all worked except for the random black images

**Comment by therysin** [comment]
Black images for static engines for me, dynamic works fine.

**Comment by Extraltodeus** [comment]
What if you try with the CFG at 1? Do you get black images?

If yes, you can try a temporary fix by modifying the sampling function found in comfy\samplers.py like this:

  
```
def sampling_function(model, x, timestep, uncond, cond, cond_scale, model_options={}, seed=None):
    if math.isclose(cond_scale, 1.0) and model_options.get("disable_cfg1_optimization", False) == False:
        uncond_ = None
    else:
        uncond_ = uncond

    out1 = calc_cond_batch(model, [cond, None], x, timestep, model_options)
    out2 = calc_cond_batch(model, [uncond_, None], x, timestep, model_options)
    return cfg_function(model, out1[0], out2[0], cond_scale, x, timestep, model_options=model_options, cond=cond, uncond=uncond_)
```

btw If you are using my node "automatic cfg" the monkeypatching will ignore this modification.

**Comment by thanayut1750** [comment]
get black image after 4th of generated, SDXL static 4 batch

**Comment by copybaras** [comment]
So what if in my case changing "batch_size" parameter for generating engine = number of black images it will make? It's only not black with CFG=1 but the results is horrible. Well it's still faster generating 2 images using TensorRT and getting 1 of them black, but I wonder why it's the case.

**Comment by bananasss00** [comment]
@Extraltodeus with your node work fine, thx

**Comment by KarinMiku** [comment]
> What if you try with the CFG at 1? Do you get black images?
> 
> If yes, you can try a temporary fix by modifying the sampling function found in comfy\samplers.py like this:
> 
> EDIT: If you use my node "[automatic-cfg](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG)" you can throw the json at the end of my answer in the presets folders and so you won't have to edit the sampling function.
> 
> ```
> def sampling_function(model, x, timestep, uncond, cond, cond_scale, model_options={}, seed=None):
>     if math.isclose(cond_scale, 1.0) and model_options.get("disable_cfg1_optimization", False) == False:
>         uncond_ = None
>     else:
>         uncond_ = uncond
> 
>     out1 = calc_cond_batch(model, [cond, None], x, timestep, model_options)
>     out2 = calc_cond_batch(model, [uncond_, None], x, timestep, model_options)
>     return cfg_function(model, out1[0], out2[0], cond_scale, x, timestep, model_options=model_options, cond=cond, uncond=uncond_)
> ```
> 
> ~btw If you are using my node "automatic cfg" the monkeypatching will ignore this modification.~
> 
> [cond_uncond_generate_separately.json](https://github.com/user-attachments/files/15688364/cond_uncond_generate_separately.json)
> 
> will look like this:
> 
> ![image](https://private-user-images.githubusercontent.com/15731540/337489491-0300bcef-5595-4882-b70e-a5d666f3a6d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Mjk0OTUsIm5iZiI6MTcxODQyOTE5NSwicGF0aCI6Ii8xNTczMTU0MC8zMzc0ODk0OTEtMDMwMGJjZWYtNTU5NS00ODgyLWI3MGUtYTVkNjY2ZjNhNmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA1MjYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyYWQzMzAyM2ZiY2U4M2MxOTRjYjI4YjU1YjhmZjRkMTdiODA4MmJmM2JkNTNkODlmNWMxMjBiMTJjOWE3MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y6T5FvIW2MoWtI4fXSVTfcW0TYsjFiAL0Hhj4hsMMck)
> 
> This magnificent banana is a workflow:
> 
> ![03387UI_00001_](https://private-user-images.githubusercontent.com/15731540/337489857-2c6c3cd0-ea62-415b-886d-e05de9e04631.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0Mjk0OTUsIm5iZiI6MTcxODQyOTE5NSwicGF0aCI6Ii8xNTczMTU0MC8zMzc0ODk4NTctMmM2YzNjZDAtZWE2Mi00MTViLTg4NmQtZTA1ZGU5ZTA0NjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA1MjYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNWMxODk1ODFmODcwOWJmYzJiZTU2YWQ2YTkwYjhhZWNhYjIzYWEyODVjMjJjNDU2ODFkZjcwOWVjYzA3YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ZLcjLPkoEKNb7JbBzDG0EUX1fUzLSKKe-4pgrdaJb4)

i have no idea what this is, but your thing fixed my issue!! lol, thank you so much!, after created and tried with static / dynamic versions of a model, for some reason, all of my images turned out black, and the only way to get something was by using cfg 1.0, but the result was horrible (just a bunch of colors and a blurry character). im not sure whats the real issue since i have a good gpu (RTX 4070) but thanks to your node i was able to change the cfg and actually get normal results

**Comment by gseth** [comment]
Most of the time, the images generated are black. Regeneration fixes it. Whenever the images are white noise, rainbow noise, or black, I get this error in cmd:

```
Q:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py:1435: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
```

Here is the video demonstration of the error:

https://github.com/comfyanonymous/ComfyUI_TensorRT/assets/6172927/36009c0f-9699-4114-90e0-466e5375dc42

This is not exclusive to SD3, it happens on sdxl as well. Trained the Juggernaut model 1024x1024 batch 4 static, same behavior.

**Comment by comfyanonymous** [comment]
Can you check if this fixes it? https://github.com/comfyanonymous/ComfyUI_TensorRT/commit/41e28c6d62db9e34922c44df25a5ccacc849382c

**Comment by aikitoria** [comment]
I will try if I can reproduce them still!

**Comment by aikitoria** [comment]
After this commit, it newly says this on first run:

```
[TRT] [W] Using default stream in enqueueV3() may lead to performance issues due to additional calls to cudaStreamSynchronize() by TensorRT to ensure correct synchronization. Please use non-default stream instead.
```

Not sure if important. So far I have not gotten any black images, even after changing prompts several times, which used to have some chance of causing it before.
